spring:
  application:
    name: sales-service
  security:
    user:
      name: breaker
      password: breaker
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false

logging:
  level:
    org:
      springframework: DEBUG

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health
